name: pretty_demo
description: A sample Polymer application
dependencies:
  enumerators: any
  paper_elements: any
  polymer: '>=0.15.1+3 <0.16.0'
  pretty:
    path: ../pretty
transformers:
- polymer:
    entry_points: web/pretty_demo.html
