name: pretty_demo
description: A sample Polymer application
dependencies:
  enumerators: any
  paper_elements: any
  polymer: '>=0.11.0-dev.2 <0.12.0'
  pretty: any
transformers:
- polymer:
    entry_points: web/pretty_demo.html
