name: pretty_demo
description: A sample Polymer application
dependencies:
  enumerators: any
  paper_elements: any
  polymer: '>=0.15.1+3 <0.16.0'
  pretty: '>= 0.1.0 <0.2.0'
transformers:
- polymer:
    entry_points: web/pretty_demo.html
